" Rommert Zijlstra's .vimrc

" Auto-install Plug
" https://github.com/junegunn/vim-plug/wiki/tips#automatic-installation
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/bundle')

packadd! cfilter       " Add Cfilter Lfitler commands
packadd! editexisting  " Open existing vim instance if open
packadd! matchit       " Make % command work better

Plug 'knubie/vim-kitty-navigator', {
  \ 'do': 'cp  ./*.py $HOME/.config/kitty/'
\}

" UI/UX related
Plug '/usr/local/opt/fzf' | Plug 'junegunn/fzf.vim'
Plug 'airblade/vim-gitgutter'
Plug 'editorconfig/editorconfig-vim'
Plug 'mattn/emmet-vim'
Plug 'vim-test/vim-test'

" Theme debugging
Plug 'gerw/vim-HiLinkTrace'

" Langage support: linters, lsp, syntax
Plug 'dense-analysis/ale'
Plug 'prabirshrestha/vim-lsp'
Plug 'rhysd/vim-lsp-ale'
Plug 'mattn/vim-lsp-settings'
Plug 'sheerun/vim-polyglot'

" Popie jopie
Plug 'tpope/vim-abolish'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-obsession'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'

call plug#end()
