version = 1

[*]
batch-size = 512
ubatch-size = 256
cache-reuse = 512
ctx-checkpoints = 32
flash-attn = on
jinja = true
mlock = true
n-gpu-layers = all
threads = 8
parallel = 2
models-max = 1

[bartowski/Qwen_Qwen3.6-35B-A3B-GGUF:Q4_K_L]
hf = bartowski/Qwen_Qwen3.6-35B-A3B-GGUF:Q4_K_L
chat-template-kwargs = {"preserve_thinking":true}
#spec-type = draft-mtp
#spec-draft-n-max = 2
ctx-size = 131071
presence-penalty = 0.1
repeat-penalty = 1.0
temp = 0.6
top-k = 20
top-p = 0.95
min-p = 0.00

[bartowski/Qwen_Qwen3.6-27B-GGUF:Q4_K_L]
hf = bartowski/Qwen_Qwen3.6-27B-GGUF:Q4_K_L
chat-template-kwargs = {"preserve_thinking":true}
cache-type-k = q8_0
cache-type-v = q8_0
#spec-type = draft-mtp
#spec-draft-n-max = 2
ctx-size = 131071
presence-penalty = 0.1
repeat-penalty = 1.0
temp = 0.6
top-k = 20
top-p = 0.95
min-p = 0.00

[bartowski/google_gemma-4-E4B-it-GGUF:Q8_0]
hf = bartowski/google_gemma-4-E4B-it-GGUF:Q8_0
chat-template-kwargs = {"enable_thinking":true}
ctx-size = 65536
repeat-penalty = 1.0
temp = 1.0
top-k = 64
top-p = 0.95

