return {
  'nvim-treesitter/nvim-treesitter',

  build = ':TSUpdate',
  config = function(_, opts)
    require('nvim-treesitter.configs').setup(opts)
  end,
  lazy = false,
  -- @type TSConfig
  opts = {
    auto_install = true,
    ensure_installed = {
      'awk',
      'bash',
      'comment',
      'css',
      'diff',
      'dockerfile',
      'embedded_template',
      -- 'gitignore',
      -- 'git_config',
      -- 'git_rebase',
      -- 'gitattributes',
      'graphql',
      'html',
      'javascript',
      'jsdoc',
      'json',
      'lua',
      'make',
      'markdown',
      'markdown_inline',
      'python',
      'regex',
      'ruby',
      'scss',
      'solidity',
      'sql',
      'svelte',
      'terraform',
      'toml',
      'tsx',
      'typescript',
      'vim',
      'vimdoc',
      'yaml',
    },
    highlight = {
      enable = true,
      disable = { 'embedded_template' },
    },
    indent = {
      enable = true,
      disable = { 'ruby' },
    },
  },
  version = false,
}
